-- Create profiles table
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  role text not null check (role in ('admin', 'manager', 'instructor', 'customer', 'guest')),
  created_at timestamptz default now()
);

-- Create instructor_details table
create table public.instructor_details (
  user_id uuid references public.profiles(id) on delete cascade not null primary key,
  certifications text[],
  lesson_types text[],
  updated_at timestamptz default now()
);

-- Create customer_details table
create table public.customer_details (
  user_id uuid references public.profiles(id) on delete cascade not null primary key,
  phone text,
  skill_level text check (skill_level in ('beginner', 'intermediate', 'advanced')),
  updated_at timestamptz default now()
);

-- Create lessons table (Catalog of lesson types)
create table public.lessons (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  duration_minutes int not null,
  price decimal(10, 2) not null,
  active boolean default true,
  created_at timestamptz default now()
);

-- Create instructor_lesson_types (Many-to-Many link)
create table public.instructor_lesson_types (
  instructor_id uuid references public.profiles(id) on delete cascade not null,
  lesson_id bigint references public.lessons(id) on delete cascade not null,
  primary key (instructor_id, lesson_id)
);

-- Create availability table
create table public.availability (
  id bigint generated by default as identity primary key,
  instructor_id uuid references public.profiles(id) on delete cascade not null,
  start_time timestamptz not null,
  end_time timestamptz not null,
  recurrence_rule text,
  created_at timestamptz default now()
);

-- Create bookings table
create table public.bookings (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.profiles(id) on delete cascade,
  instructor_id uuid references public.profiles(id) on delete set null,
  lesson_id bigint references public.lessons(id) on delete restrict not null,
  start_time timestamptz not null,
  end_time timestamptz not null,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'cancelled', 'completed', 'pending_instructor_assignment', 'pending_weather_check', 'cancelled_weather', 'cancelled_user')),
  location text,
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.instructor_details enable row level security;
alter table public.customer_details enable row level security;
alter table public.lessons enable row level security;
alter table public.instructor_lesson_types enable row level security;
alter table public.availability enable row level security;
alter table public.bookings enable row level security;

-- Default Deny Policies (Deny all access by default, to be opened up later)
create policy "Deny Public Access profiles" on public.profiles for all using (false);
create policy "Deny Public Access instructor_details" on public.instructor_details for all using (false);
create policy "Deny Public Access customer_details" on public.customer_details for all using (false);
create policy "Deny Public Access lessons" on public.lessons for all using (false);
create policy "Deny Public Access instructor_lesson_types" on public.instructor_lesson_types for all using (false);
create policy "Deny Public Access availability" on public.availability for all using (false);
create policy "Deny Public Access bookings" on public.bookings for all using (false);
