create table weather_cache (
  id bigint generated by default as identity primary key,
  location text not null, -- generic identifier like 'main_beach'
  data jsonb not null,    -- the OWM response payload
  created_at timestamp with time zone default now() not null,
  valid_until timestamp with time zone generated always as (created_at + interval '1 hour') stored
);

alter table weather_cache enable row level security;

create policy "Enable read access for authenticated users" on weather_cache for select to authenticated using (true);
create policy "Enable insert access for service_role" on weather_cache for insert to service_role with check (true);
